__app_name__ = "UsOrchestrator"
__package_name__ = "usorchestrator"
__version__ = "0.3.1"
__description__ = "A tool to automate system administration tasks on multi-hosts environments"
__author__ = "Septimiu Ujica"
__author_email__ = "me@septi.ro"
__author_url__ = "https://www.septi.ro"
__license__ = "GPLv3"
